### ISSUE TITLE
Canada - British Columbia Securities Commission - Disciplined Persons List

### ISSUE THREAD

**Issue by Kaldea** [opensanctions/crawler-planning#270] opened 2024-11-04 13:13 UTC
### Data URL

https://www.bcsc.bc.ca/enforcement/administrative-enforcement/administrative-sanctions/disciplined-list

### Publisher

British Columbia Securities Commission (BCSC)

### Publisher country/territory code

CA

### Type of data

Other risk or public interest (If none of the above fit, but there is corporate compliance or public interest in identifying these entities)

### Coverage region

region:North America

### This is a suggestion or request

- [X] I understand.

**Comment by pudo** [comment] 2024-11-25 11:03
It seems like the contents of this list are federated up into SEDAR, where they're searchable as part of a federal-level database: 

* Info: https://www.securities-administrators.ca/enforcement/disciplined-list/ 
* Data: https://www.sedarplus.ca/csa-order/viewInstance/view.html?id=5b948c1fc5c6f840095115def98c4f30b8d34a97bcc94718&_timestamp=8942357788219216

**Comment by pudo** [comment] 2024-11-25 11:11
Oh this makes it a duplicate of: https://github.com/opensanctions/crawler-planning/issues/200

**Closed by pudo** 2024-11-25 11:11 UTC
Labels: risk-list, difficulty:1, region:North America
