### ISSUE TITLE
Estonia Designated Persons under Magnitsky Amendments

### ISSUE THREAD

**Issue by Kaldea** [opensanctions/crawler-planning#219] opened 2024-06-26 13:36 UTC
### Data URL

https://vm.ee/subjektide-nimekiri-vabariigi-valitsuse-sanktsioon-seoses-olukorraga-valgevenes

### Publisher

Ministry of Foreign Affairs Estonia

### Publisher country/territory code

Estonia/ee

### Type of data

Crime/Wanted/Suspected (Persons suspected or convicted of crimes and listed by official law enforcement)

### Coverage region

region:Global

### Can you tell us more?

https://www.opensanctions.org/datasets/us_ofac_sdn/

### This is a suggestion or request

- [X] I understand.

**Comment by pudo** [comment] 2024-07-04 13:38
Duplicate of: https://github.com/opensanctions/crawler-planning/issues/202, now implemented.

**Closed by pudo** 2024-07-04 13:38 UTC
Labels: proposed, region:Global
